# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created: Tue Dec  4 22:44:33 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_preferencesDlg(object):
    def setupUi(self, preferencesDlg):
        preferencesDlg.setObjectName("preferencesDlg")
        preferencesDlg.resize(609, 438)
        self.buttonBox = QtGui.QDialogButtonBox(preferencesDlg)
        self.buttonBox.setGeometry(QtCore.QRect(430, 401, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(preferencesDlg)
        self.label.setGeometry(QtCore.QRect(31, 13, 56, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(preferencesDlg)
        self.label_2.setGeometry(QtCore.QRect(31, 40, 108, 16))
        self.label_2.setObjectName("label_2")
        self.lblComputer = QtGui.QLabel(preferencesDlg)
        self.lblComputer.setGeometry(QtCore.QRect(190, 40, 281, 16))
        self.lblComputer.setObjectName("lblComputer")
        self.lblStorage = QtGui.QLabel(preferencesDlg)
        self.lblStorage.setGeometry(QtCore.QRect(190, 124, 281, 16))
        self.lblStorage.setObjectName("lblStorage")
        self.line = QtGui.QFrame(preferencesDlg)
        self.line.setGeometry(QtCore.QRect(20, 140, 571, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.cbAutostart = QtGui.QCheckBox(preferencesDlg)
        self.cbAutostart.setGeometry(QtCore.QRect(30, 187, 491, 20))
        self.cbAutostart.setChecked(True)
        self.cbAutostart.setObjectName("cbAutostart")
        self.cbShowsync = QtGui.QCheckBox(preferencesDlg)
        self.cbShowsync.setGeometry(QtCore.QRect(30, 217, 501, 20))
        self.cbShowsync.setChecked(True)
        self.cbShowsync.setObjectName("cbShowsync")
        self.line_2 = QtGui.QFrame(preferencesDlg)
        self.line_2.setGeometry(QtCore.QRect(20, 237, 571, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.rbProxy = QtGui.QRadioButton(preferencesDlg)
        self.rbProxy.setGeometry(QtCore.QRect(30, 257, 291, 20))
        self.rbProxy.setObjectName("rbProxy")
        self.rbDirect = QtGui.QRadioButton(preferencesDlg)
        self.rbDirect.setGeometry(QtCore.QRect(30, 287, 471, 20))
        self.rbDirect.setObjectName("rbDirect")
        self.label_3 = QtGui.QLabel(preferencesDlg)
        self.label_3.setGeometry(QtCore.QRect(30, 94, 121, 16))
        self.label_3.setObjectName("label_3")
        self.txtUrl = QtGui.QLineEdit(preferencesDlg)
        self.txtUrl.setEnabled(False)
        self.txtUrl.setGeometry(QtCore.QRect(190, 94, 291, 22))
        self.txtUrl.setObjectName("txtUrl")
        self.btnDisconnect = QtGui.QPushButton(preferencesDlg)
        self.btnDisconnect.setGeometry(QtCore.QRect(493, 10, 101, 32))
        self.btnDisconnect.setObjectName("btnDisconnect")
        self.label_4 = QtGui.QLabel(preferencesDlg)
        self.label_4.setGeometry(QtCore.QRect(30, 66, 131, 20))
        self.label_4.setObjectName("label_4")
        self.txtCloudfolder = QtGui.QLineEdit(preferencesDlg)
        self.txtCloudfolder.setEnabled(False)
        self.txtCloudfolder.setGeometry(QtCore.QRect(190, 63, 291, 22))
        self.txtCloudfolder.setObjectName("txtCloudfolder")
        self.line_3 = QtGui.QFrame(preferencesDlg)
        self.line_3.setGeometry(QtCore.QRect(20, 307, 571, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.cbEnablelog = QtGui.QCheckBox(preferencesDlg)
        self.cbEnablelog.setGeometry(QtCore.QRect(30, 327, 201, 20))
        self.cbEnablelog.setObjectName("cbEnablelog")
        self.label_5 = QtGui.QLabel(preferencesDlg)
        self.label_5.setGeometry(QtCore.QRect(32, 357, 121, 16))
        self.label_5.setObjectName("label_5")
        self.txtLogfile = QtGui.QLineEdit(preferencesDlg)
        self.txtLogfile.setEnabled(False)
        self.txtLogfile.setGeometry(QtCore.QRect(190, 354, 291, 22))
        self.txtLogfile.setObjectName("txtLogfile")
        self.btnBrowsefolder = QtGui.QPushButton(preferencesDlg)
        self.btnBrowsefolder.setGeometry(QtCore.QRect(499, 64, 21, 20))
        self.btnBrowsefolder.setObjectName("btnBrowsefolder")
        self.btnBrowselog = QtGui.QPushButton(preferencesDlg)
        self.btnBrowselog.setGeometry(QtCore.QRect(480, 350, 51, 32))
        self.btnBrowselog.setObjectName("btnBrowselog")
        self.txtAccount = QtGui.QLineEdit(preferencesDlg)
        self.txtAccount.setEnabled(False)
        self.txtAccount.setGeometry(QtCore.QRect(190, 14, 291, 22))
        self.txtAccount.setObjectName("txtAccount")
        self.checkBox = QtGui.QCheckBox(preferencesDlg)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(30, 156, 411, 20))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.btnProxy = QtGui.QPushButton(preferencesDlg)
        self.btnProxy.setGeometry(QtCore.QRect(473, 255, 121, 32))
        self.btnProxy.setObjectName("btnProxy")

        self.retranslateUi(preferencesDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), preferencesDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), preferencesDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(preferencesDlg)

    def retranslateUi(self, preferencesDlg):
        preferencesDlg.setWindowTitle(QtGui.QApplication.translate("preferencesDlg", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("preferencesDlg", "Account:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("preferencesDlg", "Computer Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblComputer.setText(QtGui.QApplication.translate("preferencesDlg", "computer name here", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStorage.setText(QtGui.QApplication.translate("preferencesDlg", "used storage here", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAutostart.setText(QtGui.QApplication.translate("preferencesDlg", "Start CloudDesk sync automatically when starting this computer", None, QtGui.QApplication.UnicodeUTF8))
        self.cbShowsync.setText(QtGui.QApplication.translate("preferencesDlg", "Show files sync status icons", None, QtGui.QApplication.UnicodeUTF8))
        self.rbProxy.setText(QtGui.QApplication.translate("preferencesDlg", "Use Proxy Server", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDirect.setText(QtGui.QApplication.translate("preferencesDlg", "Direct connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("preferencesDlg", "CloudDesk Url", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDisconnect.setText(QtGui.QApplication.translate("preferencesDlg", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("preferencesDlg", "CloudDesk folder", None, QtGui.QApplication.UnicodeUTF8))
        self.cbEnablelog.setText(QtGui.QApplication.translate("preferencesDlg", "Enable logging", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("preferencesDlg", "Log file", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowsefolder.setText(QtGui.QApplication.translate("preferencesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowselog.setText(QtGui.QApplication.translate("preferencesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("preferencesDlg", "Show notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProxy.setText(QtGui.QApplication.translate("preferencesDlg", "Proxy Config...", None, QtGui.QApplication.UnicodeUTF8))

