# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created: Sat Dec 15 13:00:56 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_preferencesDlg(object):
    def setupUi(self, preferencesDlg):
        preferencesDlg.setObjectName("preferencesDlg")
        preferencesDlg.resize(580, 425)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(preferencesDlg.sizePolicy().hasHeightForWidth())
        preferencesDlg.setSizePolicy(sizePolicy)
        preferencesDlg.setMinimumSize(QtCore.QSize(580, 425))
        self.widget = QtGui.QWidget(preferencesDlg)
        self.widget.setGeometry(QtCore.QRect(11, 13, 585, 481))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.widget)
        self.label.setCursor(QtCore.Qt.ArrowCursor)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtAccount = QtGui.QLineEdit(self.widget)
        self.txtAccount.setEnabled(False)
        self.txtAccount.setMinimumSize(QtCore.QSize(250, 22))
        self.txtAccount.setMaxLength(50)
        self.txtAccount.setObjectName("txtAccount")
        self.gridLayout.addWidget(self.txtAccount, 0, 1, 1, 1)
        self.btnDisconnect = QtGui.QPushButton(self.widget)
        self.btnDisconnect.setObjectName("btnDisconnect")
        self.gridLayout.addWidget(self.btnDisconnect, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lblComputer = QtGui.QLabel(self.widget)
        self.lblComputer.setMinimumSize(QtCore.QSize(0, 22))
        self.lblComputer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblComputer.setObjectName("lblComputer")
        self.gridLayout.addWidget(self.lblComputer, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtCloudfolder = QtGui.QLineEdit(self.widget)
        self.txtCloudfolder.setEnabled(False)
        self.txtCloudfolder.setMinimumSize(QtCore.QSize(250, 22))
        self.txtCloudfolder.setObjectName("txtCloudfolder")
        self.gridLayout.addWidget(self.txtCloudfolder, 2, 1, 1, 1)
        self.btnBrowsefolder = QtGui.QPushButton(self.widget)
        self.btnBrowsefolder.setObjectName("btnBrowsefolder")
        self.gridLayout.addWidget(self.btnBrowsefolder, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.txtUrl = QtGui.QLineEdit(self.widget)
        self.txtUrl.setEnabled(True)
        self.txtUrl.setMinimumSize(QtCore.QSize(250, 22))
        self.txtUrl.setObjectName("txtUrl")
        self.gridLayout.addWidget(self.txtUrl, 3, 1, 1, 1)
        self.lblStorage = QtGui.QLabel(self.widget)
        self.lblStorage.setMinimumSize(QtCore.QSize(0, 22))
        self.lblStorage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblStorage.setObjectName("lblStorage")
        self.gridLayout.addWidget(self.lblStorage, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.btnSelect = QtGui.QPushButton(self.widget)
        self.btnSelect.setObjectName("btnSelect")
        self.gridLayout.addWidget(self.btnSelect, 5, 2, 1, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbNotifications = QtGui.QCheckBox(self.widget)
        self.cbNotifications.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbNotifications.sizePolicy().hasHeightForWidth())
        self.cbNotifications.setSizePolicy(sizePolicy)
        self.cbNotifications.setMinimumSize(QtCore.QSize(200, 22))
        self.cbNotifications.setMouseTracking(False)
        self.cbNotifications.setChecked(True)
        self.cbNotifications.setObjectName("cbNotifications")
        self.verticalLayout.addWidget(self.cbNotifications)
        self.cbAutostart = QtGui.QCheckBox(self.widget)
        self.cbAutostart.setMinimumSize(QtCore.QSize(0, 22))
        self.cbAutostart.setChecked(True)
        self.cbAutostart.setObjectName("cbAutostart")
        self.verticalLayout.addWidget(self.cbAutostart)
        self.cbIconOverlays = QtGui.QCheckBox(self.widget)
        self.cbIconOverlays.setMinimumSize(QtCore.QSize(0, 22))
        self.cbIconOverlays.setChecked(True)
        self.cbIconOverlays.setObjectName("cbIconOverlays")
        self.verticalLayout.addWidget(self.cbIconOverlays)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_4 = QtGui.QFrame(self.widget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbProxy = QtGui.QRadioButton(self.widget)
        self.rbProxy.setObjectName("rbProxy")
        self.gridLayout_2.addWidget(self.rbProxy, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(278, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.btnProxy = QtGui.QPushButton(self.widget)
        self.btnProxy.setObjectName("btnProxy")
        self.gridLayout_2.addWidget(self.btnProxy, 0, 2, 1, 1)
        self.rbDirect = QtGui.QRadioButton(self.widget)
        self.rbDirect.setObjectName("rbDirect")
        self.gridLayout_2.addWidget(self.rbDirect, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(398, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.line_3 = QtGui.QFrame(self.widget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtLogfile = QtGui.QLineEdit(self.widget)
        self.txtLogfile.setEnabled(False)
        self.txtLogfile.setMinimumSize(QtCore.QSize(380, 22))
        self.txtLogfile.setObjectName("txtLogfile")
        self.gridLayout_3.addWidget(self.txtLogfile, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(328, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 2)
        self.cbEnablelog = QtGui.QCheckBox(self.widget)
        self.cbEnablelog.setObjectName("cbEnablelog")
        self.gridLayout_3.addWidget(self.cbEnablelog, 0, 0, 1, 1)
        self.btnBrowselog = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBrowselog.sizePolicy().hasHeightForWidth())
        self.btnBrowselog.setSizePolicy(sizePolicy)
        self.btnBrowselog.setMinimumSize(QtCore.QSize(32, 32))
        self.btnBrowselog.setBaseSize(QtCore.QSize(0, 0))
        self.btnBrowselog.setObjectName("btnBrowselog")
        self.gridLayout_3.addWidget(self.btnBrowselog, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(19)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtGui.QSpacerItem(408, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(7, 1)

        self.retranslateUi(preferencesDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), preferencesDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), preferencesDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(preferencesDlg)
        preferencesDlg.setTabOrder(self.txtAccount, self.btnDisconnect)
        preferencesDlg.setTabOrder(self.btnDisconnect, self.txtCloudfolder)
        preferencesDlg.setTabOrder(self.txtCloudfolder, self.btnBrowsefolder)
        preferencesDlg.setTabOrder(self.btnBrowsefolder, self.txtUrl)
        preferencesDlg.setTabOrder(self.txtUrl, self.cbNotifications)
        preferencesDlg.setTabOrder(self.cbNotifications, self.cbAutostart)
        preferencesDlg.setTabOrder(self.cbAutostart, self.cbIconOverlays)
        preferencesDlg.setTabOrder(self.cbIconOverlays, self.rbProxy)
        preferencesDlg.setTabOrder(self.rbProxy, self.btnProxy)
        preferencesDlg.setTabOrder(self.btnProxy, self.rbDirect)
        preferencesDlg.setTabOrder(self.rbDirect, self.cbEnablelog)
        preferencesDlg.setTabOrder(self.cbEnablelog, self.txtLogfile)
        preferencesDlg.setTabOrder(self.txtLogfile, self.btnBrowselog)
        preferencesDlg.setTabOrder(self.btnBrowselog, self.buttonBox)

    def retranslateUi(self, preferencesDlg):
        preferencesDlg.setWindowTitle(QtGui.QApplication.translate("preferencesDlg", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("preferencesDlg", "Account:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDisconnect.setToolTip(QtGui.QApplication.translate("preferencesDlg", "Link and unlink this device", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDisconnect.setText(QtGui.QApplication.translate("preferencesDlg", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("preferencesDlg", "Computer Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblComputer.setText(QtGui.QApplication.translate("preferencesDlg", "computer name here", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("preferencesDlg", "CloudDesk location", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowsefolder.setToolTip(QtGui.QApplication.translate("preferencesDlg", "Change the CloudDesk folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowsefolder.setText(QtGui.QApplication.translate("preferencesDlg", "Change...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("preferencesDlg", "CloudDesk Url", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStorage.setText(QtGui.QApplication.translate("preferencesDlg", "used storage here", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("preferencesDlg", "Folders to synchronize", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelect.setText(QtGui.QApplication.translate("preferencesDlg", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbNotifications.setText(QtGui.QApplication.translate("preferencesDlg", "Show notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAutostart.setText(QtGui.QApplication.translate("preferencesDlg", "Start CloudDesk sync automatically when starting this computer", None, QtGui.QApplication.UnicodeUTF8))
        self.cbIconOverlays.setText(QtGui.QApplication.translate("preferencesDlg", "Show files sync status icons", None, QtGui.QApplication.UnicodeUTF8))
        self.rbProxy.setText(QtGui.QApplication.translate("preferencesDlg", "Use Proxy Server", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProxy.setText(QtGui.QApplication.translate("preferencesDlg", "Proxy Config...", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDirect.setText(QtGui.QApplication.translate("preferencesDlg", "Direct connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("preferencesDlg", "Log file", None, QtGui.QApplication.UnicodeUTF8))
        self.cbEnablelog.setText(QtGui.QApplication.translate("preferencesDlg", "Enable logging", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowselog.setText(QtGui.QApplication.translate("preferencesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))

