# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created: Sat Feb  9 19:57:49 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_preferencesDlg(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
#        Dialog.setSizePolicy(QtGui.QSizePolicy.Policy.Fixed, QtGui.QSizePolicy.Policy.Fixed)
        Dialog.setFixedSize(520, 251)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 5, 521, 201))
        self.tabWidget.setIconSize(QtCore.QSize(48, 48))
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.layoutWidget = QtGui.QWidget(self.tabGeneral)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 491, 70))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbNotifications = QtGui.QCheckBox(self.layoutWidget)
        self.cbNotifications.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbNotifications.sizePolicy().hasHeightForWidth())
        self.cbNotifications.setSizePolicy(sizePolicy)
        self.cbNotifications.setMinimumSize(QtCore.QSize(200, 22))
        self.cbNotifications.setMouseTracking(False)
        self.cbNotifications.setChecked(True)
        self.cbNotifications.setObjectName("cbNotifications")
        self.verticalLayout.addWidget(self.cbNotifications)
        self.cbAutostart = QtGui.QCheckBox(self.layoutWidget)
        self.cbAutostart.setMinimumSize(QtCore.QSize(0, 22))
        self.cbAutostart.setChecked(True)
        self.cbAutostart.setObjectName("cbAutostart")
        self.verticalLayout.addWidget(self.cbAutostart)
        self.cbIconOverlays = QtGui.QCheckBox(self.layoutWidget)
        self.cbIconOverlays.setMinimumSize(QtCore.QSize(0, 22))
        self.cbIconOverlays.setChecked(True)
        self.cbIconOverlays.setObjectName("cbIconOverlays")
        self.verticalLayout.addWidget(self.cbIconOverlays)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../nxdrive/data/icons/general-configuration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabGeneral, icon, "")
        self.tabAccount = QtGui.QWidget()
        self.tabAccount.setObjectName("tabAccount")
        self.widget = QtGui.QWidget(self.tabAccount)
        self.widget.setGeometry(QtCore.QRect(11, 5, 487, 150))
        self.widget.setObjectName("widget")
        self.vLayout = QtGui.QVBoxLayout(self.widget)
        self.groupboxSite = QtGui.QGroupBox(self.widget) 
        self.groupboxSite.setFlat(True)
        self.vLayout.addWidget(self.groupboxSite)
        self.gridLayout = QtGui.QGridLayout(self.groupboxSite)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupboxSite.setLayout(self.gridLayout)
        self.label = QtGui.QLabel(self.widget)
        self.label.setCursor(QtCore.Qt.ArrowCursor)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtAccount = QtGui.QLineEdit(self.widget)
        self.txtAccount.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAccount.sizePolicy().hasHeightForWidth())
        self.txtAccount.setSizePolicy(sizePolicy)
        self.txtAccount.setMinimumSize(QtCore.QSize(250, 22))
        self.txtAccount.setMaxLength(50)
        self.txtAccount.setObjectName("txtAccount")
        self.gridLayout.addWidget(self.txtAccount, 0, 1, 1, 1)
        self.btnDisconnect = QtGui.QPushButton(self.widget)
        self.btnDisconnect.setObjectName("btnDisconnect")
        self.gridLayout.addWidget(self.btnDisconnect, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtUrl = QtGui.QLineEdit(self.widget)
        self.txtUrl.setEnabled(True)
        self.txtUrl.setMinimumSize(QtCore.QSize(250, 22))
        self.txtUrl.setObjectName("txtUrl")
        self.gridLayout.addWidget(self.txtUrl, 1, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.lblStorage = QtGui.QLabel(self.widget)
        self.lblStorage.setMinimumSize(QtCore.QSize(0, 22))
        self.lblStorage.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblStorage.setObjectName("lblStorage")
        self.gridLayout.addWidget(self.lblStorage, 2, 1, 1, 1)
#        self.hLayout = QtGui.QHBoxLayout()
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 22))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
#        self.hLayout.addWidget(self.label_2)
#        self.hLayout.addStretch(1)
        self.lblComputer = QtGui.QLabel(self.widget)
        self.lblComputer.setMinimumSize(QtCore.QSize(250, 22))
        self.lblComputer.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblComputer.setObjectName("lblComputer")
        self.gridLayout.addWidget(self.lblComputer, 3, 1, 1, 1)
#        self.hLayout.addWidget(self.lblComputer)
#        self.hLine = QtGui.QFrame()
#        self.hLine.setFrameStyle(QtGui.QFrame.HLine)
#        self.hLine.setLineWidth(0)
#        self.vLayout.addStretch(1)
#        self.vLayout.addWidget(self.hLine)
#        self.vLayout.addLayout(self.hLayout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../nxdrive/data/icons/user-account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabAccount, icon1, "")
        self.tabNetwork = QtGui.QWidget()
        self.tabNetwork.setObjectName("tabNetwork")
        self.layoutWidget1 = QtGui.QWidget(self.tabNetwork)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 308, 110))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbProxy = QtGui.QRadioButton(self.layoutWidget1)
        self.rbProxy.setMinimumSize(QtCore.QSize(0, 32))
        self.rbProxy.setObjectName("rbProxy")
        self.gridLayout_2.addWidget(self.rbProxy, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(18, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.btnProxy = QtGui.QPushButton(self.layoutWidget1)
        self.btnProxy.setObjectName("btnProxy")
        self.gridLayout_2.addWidget(self.btnProxy, 0, 2, 1, 1)
        self.rbAutodetect = QtGui.QRadioButton(self.layoutWidget1)
        self.rbAutodetect.setMinimumSize(QtCore.QSize(0, 32))
        self.rbAutodetect.setObjectName("rbAutodetect")
        self.gridLayout_2.addWidget(self.rbAutodetect, 1, 0, 1, 1)
        self.rbDirect = QtGui.QRadioButton(self.layoutWidget1)
        self.rbDirect.setMinimumSize(QtCore.QSize(0, 32))
        self.rbDirect.setObjectName("rbDirect")
        self.gridLayout_2.addWidget(self.rbDirect, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(156, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../nxdrive/data/icons/network-proxy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabNetwork, icon2, "")
        self.tabAdvanced = QtGui.QWidget()
        self.tabAdvanced.setObjectName("tabAdvanced")
        self.layoutWidget2 = QtGui.QWidget(self.tabAdvanced)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 5, 495, 135))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        # Folder location
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.txtCloudfolder = QtGui.QLineEdit(self.layoutWidget2)
        self.txtCloudfolder.setEnabled(False)
        self.txtCloudfolder.setMinimumSize(QtCore.QSize(250, 22))
        self.txtCloudfolder.setObjectName("txtCloudfolder")
        self.gridLayout_3.addWidget(self.txtCloudfolder, 0, 1, 1, 1)
        self.btnBrowsefolder = QtGui.QPushButton(self.layoutWidget2)
        self.btnBrowsefolder.setMinimumSize(QtCore.QSize(100, 32))
        self.btnBrowsefolder.setObjectName("btnBrowsefolder")
        self.gridLayout_3.addWidget(self.btnBrowsefolder, 0, 2, 1, 1)
        # Folders to synchronize
        self.label_9 = QtGui.QLabel(self.layoutWidget2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 22))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 1, 1, 1)
        self.btnSelect = QtGui.QPushButton(self.layoutWidget2)
        self.btnSelect.setMinimumSize(QtCore.QSize(100, 32))
        self.btnSelect.setObjectName("btnSelect")
#        self.gridLayout_3.addWidget(self.btnSelect, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.btnSelect, 1, 2, 1, 1)
#        self.btnBrowselog = QtGui.QPushButton(self.layoutWidget2)
#        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.btnBrowselog.sizePolicy().hasHeightForWidth())
#        self.btnBrowselog.setSizePolicy(sizePolicy)
#        self.btnBrowselog.setMinimumSize(QtCore.QSize(100, 32))
#        self.btnBrowselog.setBaseSize(QtCore.QSize(0, 0))
#        self.btnBrowselog.setObjectName("btnBrowselog")
#        self.gridLayout_3.addWidget(self.btnBrowselog, 1, 2, 1, 1)

#        self.txtLogfile = QtGui.QLineEdit(self.layoutWidget2)
#        self.txtLogfile.setEnabled(False)
#        self.txtLogfile.setMinimumSize(QtCore.QSize(250, 22))
#        self.txtLogfile.setObjectName("txtLogfile")
#        self.gridLayout_3.addWidget(self.txtLogfile, 1, 1, 1, 1)
#        self.cbEnablelog = QtGui.QCheckBox(self.layoutWidget2)
#        self.cbEnablelog.setObjectName("cbEnablelog")
#        self.gridLayout_3.addWidget(self.cbEnablelog, 1, 0, 1, 1)

        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../nxdrive/data/icons/advanced.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabAdvanced, icon3, "")
        self.layoutWidget3 = QtGui.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 210, 501, 34))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(338, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget3)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.cbNotifications.setText(QtGui.QApplication.translate("Dialog", "Show notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAutostart.setText(QtGui.QApplication.translate("Dialog", "Start %s automatically when starting this computer", None, QtGui.QApplication.UnicodeUTF8))
        self.cbIconOverlays.setText(QtGui.QApplication.translate("Dialog", "Show files sync status icons", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), QtGui.QApplication.translate("Dialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Account:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDisconnect.setToolTip(QtGui.QApplication.translate("Dialog", "Link and unlink this device", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDisconnect.setText(QtGui.QApplication.translate("Dialog", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "CloudDesk Url", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Computer Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblComputer.setText(QtGui.QApplication.translate("Dialog", "computer name here", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Storage Used:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStorage.setText(QtGui.QApplication.translate("Dialog", "used storage here", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAccount), QtGui.QApplication.translate("Dialog", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.rbProxy.setText(QtGui.QApplication.translate("Dialog", "Use Proxy Server", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProxy.setText(QtGui.QApplication.translate("Dialog", "Proxy Config...", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAutodetect.setText(QtGui.QApplication.translate("Dialog", "Auto-detect", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDirect.setText(QtGui.QApplication.translate("Dialog", "Direct connection", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNetwork), QtGui.QApplication.translate("Dialog", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Folders to synchronize", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelect.setText(QtGui.QApplication.translate("Dialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
#        self.btnBrowselog.setText(QtGui.QApplication.translate("Dialog", "Change...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowsefolder.setToolTip(QtGui.QApplication.translate("Dialog", "Change the CloudDesk folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowsefolder.setText(QtGui.QApplication.translate("Dialog", "Change...", None, QtGui.QApplication.UnicodeUTF8))
#        self.cbEnablelog.setText(QtGui.QApplication.translate("Dialog", "Enable logging", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "CloudDesk location", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdvanced), QtGui.QApplication.translate("Dialog", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.groupboxSite.setTitle(QtGui.QApplication.translate("Dialog", "Site Information", None, QtGui.QApplication.UnicodeUTF8))
